apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: webfrontend
  name: webfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webfrontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webfrontend
    spec:
      containers:
      - image: webfrontend
        name: webfrontend
        resources: {}
status: {}
